name: USWDS Bootstrap Layout Builder Configuration - Media Library
type: module
description: Configuration for using USWDS with layout builder and media library. (WARNING DOESN'T WORK WELL)
core_version_requirement: ^9 || ^10 || ^11
package: 'Layout Builder'
dependencies:
  - uswds_blb_configuration:uswds_blb_configuration
  - drupal:media_library
