name: USWDS Layout Builder Configuration
type: module
description: Configuration for using USWDS in layout builder.
core_version_requirement: ^9 || ^10
configure: uswds_blb_configuration.settings
package: 'Layout Builder'
dependencies:
  - drupal:layout_builder
  - drupal:media_library
